name: Evaporative Humidifier Driver
packageKey: com.svd.switchbotevamhumidifier
profiles:
  - id: evaporative-humidifier.v1
    name: Evaporative Humidifier
permissions:
  - location
metadata:
  vid: evaporative-humidifier-v1
  mnmn: SmartThingsCommunity
